// <auto-generated />
using EmailSender.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EmailSender.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210110154631_addtopics")]
    partial class addtopics
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("EmailSender.Models.Topic", b =>
                {
                    b.Property<int>("TopicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Topic_name")
                        .HasColumnType("TEXT");

                    b.HasKey("TopicId");

                    b.ToTable("Topics");

                    b.HasData(
                        new
                        {
                            TopicId = 1,
                            Topic_name = "news"
                        },
                        new
                        {
                            TopicId = 2,
                            Topic_name = "finance"
                        },
                        new
                        {
                            TopicId = 3,
                            Topic_name = "sport"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
